# Generated by Django 5.0.6 on 2024-06-06 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_user', '0002_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='user',
            new_name='user_id',
        ),
    ]
